name: Docker Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 登录 GitHub Package Registry
      - name: Log in to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/harmonyos-ci-image:latest .

      # 4. 推送 Docker 镜像到 GitHub Package Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/harmonyos-ci-image:latest

      # 5. 可选：标记镜像为特定版本（如果推送标签时触发）
      - name: Tag and push versioned image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{ github.repository }}/harmonyos-ci-image:latest ghcr.io/${{ github.repository }}/harmonyos-ci-image:$TAG
          docker push ghcr.io/${{ github.repository }}/harmonyos-ci-image:$TAG
